# Notebook 2: Transform data records into dataframes

Import the Python library dependencies.

In [1]:
import pathlib

import polars as pl
import watermark

Run a "watermark" to show which library versions are used in this notebook's runtime environment.

In [2]:
%load_ext watermark
%watermark
%watermark --iversions

Last updated: 2025-11-12T10:48:10.763408-08:00

Python implementation: CPython
Python version       : 3.13.8
IPython version      : 9.1.0

Compiler    : Clang 17.0.0 (clang-1700.0.13.3)
OS          : Darwin
Release     : 24.6.0
Machine     : arm64
Processor   : arm
CPU cores   : 14
Architecture: 64bit

watermark: 2.5.0
polars   : 1.29.0

## Parse the OpenSanctions dataset

In [3]:
df_src: pl.DataFrame = pl.read_ndjson("data/open-sanctions.json")

# normalize IRIs for connecting later
df_src = df_src.replace_column(
    1,
    pl.Series(
        "id",
        map(lambda s: "sz:ds_open-sanctions_" + s, df_src["RECORD_ID"])
    ),
)

df_src = df_src.replace_column(
    2,
    pl.Series(
        "class",
        map(lambda s: "sz:" + s.capitalize(), df_src["RECORD_TYPE"])
    ),
)

In [4]:
df_src

shape: (24, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ DATA_SOUR ┆ id        ┆ class     ┆ LAST_CHAN ┆ … ┆ SOURCE_LI ┆ RELATIONS ┆ URL       ┆ CONTACTS │
│ CE        ┆ ---       ┆ ---       ┆ GE        ┆   ┆ NKS       ┆ HIPS      ┆ ---       ┆ ---      │
│ ---       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ list[str │
│ str       ┆           ┆           ┆ str       ┆   ┆ list[stru ┆ list[stru ┆           ┆ uct[1]]  │
│           ┆           ┆           ┆           ┆   ┆ ct[1]]    ┆ ct[5]]    ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Person ┆ 2024-07-3 ┆ … ┆ [{"https: ┆ [{"Direct ┆ https://w ┆ null     │
│ TIONS     ┆ n-sanctio ┆           ┆ 0T16:41:1 ┆   ┆ //find-an ┆ orship"," ┆ ww.opensa ┆          │
│           ┆ ns_NK-25v ┆           ┆ 4         ┆   ┆ d-update. ┆ OPEN-SANC ┆ nctions.o ┆          │
│           ┆ yVF…      ┆           ┆           ┆   ┆ com…      ┆ TIO…      ┆ rg/…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2025-01-0 ┆ … ┆ null      ┆ [{null,nu ┆ https://w ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 7T00:33:0 ┆   ┆           ┆ ll,null," ┆ ww.opensa ┆          │
│           ┆ ns_NK-3p3 ┆           ┆ 3         ┆   ┆           ┆ OPEN-SANC ┆ nctions.o ┆          │
│           ┆ mmV…      ┆           ┆           ┆   ┆           ┆ TIO…      ┆ rg/…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-03-0 ┆ … ┆ null      ┆ [{null,nu ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 3T19:51:2 ┆   ┆           ┆ ll,null," ┆ pensancti ┆          │
│           ┆ ns_NK-auy ┆           ┆ 9         ┆   ┆           ┆ OPEN-SANC ┆ ons.org/e ┆          │
│           ┆ PsL…      ┆           ┆           ┆   ┆           ┆ TIO…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-03-0 ┆ … ┆ [{"http:/ ┆ [{null,nu ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 3T08:46:3 ┆   ┆ /business ┆ ll,null," ┆ pensancti ┆          │
│           ┆ ns_NK-cf4 ┆           ┆ 1         ┆   ┆ .data.gov ┆ OPEN-SANC ┆ ons.org/e ┆          │
│           ┆ Q3K…      ┆           ┆           ┆   ┆ .uk…      ┆ TIO…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Person ┆ 2025-02-1 ┆ … ┆ [{"https: ┆ [{"Family ┆ https://w ┆ null     │
│ TIONS     ┆ n-sanctio ┆           ┆ 0T15:38:0 ┆   ┆ //sanctio ┆ ","OPEN-S ┆ ww.opensa ┆          │
│           ┆ ns_NK-dNN ┆           ┆ 2         ┆   ┆ nssearch. ┆ ANCTIONS" ┆ nctions.o ┆          │
│           ┆ N56…      ┆           ┆           ┆   ┆ ofa…      ┆ ,"Q…      ┆ rg/…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{null,nu ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ll,null," ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ OPEN-SANC ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ TIO…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{null,nu ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ll,null," ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ OPEN-SANC ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ TIO…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{null,nu ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ll,null," ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ OPEN-SANC ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ TIO…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{null,nu ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ll,null," ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ OPEN-SANC ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ TIO…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{null,nu ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ll,null," ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ OPEN-SANC ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ TIO…      ┆ nti…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# normalize names from nested attributes
df: pl.DataFrame = df_src.explode("NAMES")

df = df.with_columns(
    pl.when(pl.col("NAMES").struct.field("NAME_TYPE") == "PRIMARY_NAME_FULL")
    .then(pl.col("NAMES").struct.field("NAME_TYPE"))
    .when(pl.col("NAMES").struct.field("NAME_TYPE") == "PRIMARY")
    .then(
        pl.coalesce(
            pl.col("NAMES").struct.field("NAME_FULL"),
            pl.col("NAMES").struct.field("NAME_ORG")
        )
    )
    .otherwise(None)
    .alias("descrip")
)

# select the columns to keep
df = df.select(
        pl.col("id"),
        pl.col("descrip"),
        pl.col("class"),
        pl.col("ADDRESSES").alias("addr"),
        pl.col("URL").alias("url"),
    ).drop_nulls(subset=["descrip"]).sort("id")

# normalize addresses from nested attributes
df = df.explode("addr")

df = df.with_columns(
    pl.when(pl.col("addr").is_not_null())
    .then(
        pl.coalesce(
            pl.col("addr").struct.field("ADDR_FULL"),
        )
    )
    .otherwise(None)
    .alias("addr")
)

df

shape: (75, 5)
┌────────────────────┬───────────────────┬─────────────────┬───────────────────┬───────────────────┐
│ id                 ┆ descrip           ┆ class           ┆ addr              ┆ url               │
│ ---                ┆ ---               ┆ ---             ┆ ---               ┆ ---               │
│ str                ┆ str               ┆ str             ┆ str               ┆ str               │
╞════════════════════╪═══════════════════╪═════════════════╪═══════════════════╪═══════════════════╡
│ sz:ds_open-sanctio ┆ Abassin BADSHAH   ┆ sz:Person       ┆ 31 Quernmore      ┆ https://www.opens │
│ ns_NK-25vyVF…      ┆                   ┆                 ┆ Close, Bromley,   ┆ anctions.org/…    │
│                    ┆                   ┆                 ┆ K…                ┆                   │
│ sz:ds_open-sanctio ┆ LMAR (GB) LTD     ┆ sz:Organization ┆ 31 Quernmore      ┆ https://www.opens │
│ ns_NK-3p3mmV…      ┆                   ┆                 ┆ Close, Bromley,   ┆ anctions.org/…    │
│                    ┆                   ┆                 ┆ K…                ┆                   │
│ sz:ds_open-sanctio ┆ Gulnara           ┆ sz:Person       ┆ MOSCOW, RUS,      ┆ https://www.opens │
│ ns_NK-L2UmsZ…      ┆ Suleimanova       ┆                 ┆ 123430            ┆ anctions.org/…    │
│                    ┆ KERIMOVA          ┆                 ┆                   ┆                   │
│ sz:ds_open-sanctio ┆ Gulnara           ┆ sz:Person       ┆ Apt 270, Build.   ┆ https://www.opens │
│ ns_NK-L2UmsZ…      ┆ Suleimanova       ┆                 ┆ 31, Pyatnitsko…   ┆ anctions.org/…    │
│                    ┆ KERIMOVA          ┆                 ┆                   ┆                   │
│ sz:ds_open-sanctio ┆ Gulnara           ┆ sz:Person       ┆ Apt 270, Build.   ┆ https://www.opens │
│ ns_NK-L2UmsZ…      ┆ Suleimanova       ┆                 ┆ 31, Pyatnitsko…   ┆ anctions.org/…    │
│                    ┆ KERIMOVA          ┆                 ┆                   ┆                   │
│ …                  ┆ …                 ┆ …               ┆ …                 ┆ …                 │
│ sz:ds_open-sanctio ┆ Vencher           ┆ sz:Organization ┆ ПЕР.              ┆ https://opensanct │
│ ns_rupep-com…      ┆ Management        ┆                 ┆ СТАРОМОНЕТНЫЙ,    ┆ ions.org/enti…    │
│                    ┆ Limited LLC       ┆                 ┆ Москва            ┆                   │
│ sz:ds_open-sanctio ┆ Natsionalnaia     ┆ sz:Organization ┆ переулок          ┆ https://opensanct │
│ ns_rupep-com…      ┆ Kinoset LLC       ┆                 ┆ Старомонетны,     ┆ ions.org/enti…    │
│                    ┆                   ┆                 ┆ Москва            ┆                   │
│ sz:ds_open-sanctio ┆ Zareche-Estate    ┆ sz:Organization ┆ улица Народная,   ┆ https://opensanct │
│ ns_rupep-com…      ┆ LLC               ┆                 ┆ Москва            ┆ ions.org/enti…    │
│ sz:ds_open-sanctio ┆ NUGGET CAPITAL    ┆ sz:Organization ┆ null              ┆ https://opensanct │
│ ns_rupep-com…      ┆ PLC               ┆                 ┆                   ┆ ions.org/enti…    │
│ sz:ds_open-sanctio ┆ POLYUS FINANCE    ┆ sz:Organization ┆ null              ┆ https://opensanct │
│ ns_rupep-com…      ┆ PLC               ┆                 ┆                   ┆ ions.org/enti…    │
└────────────────────┴───────────────────┴─────────────────┴───────────────────┴───────────────────┘

Serialize this dataframe to the `os_data.csv` CSV file.

In [6]:
df.write_csv(pathlib.Path("os_data.csv"), separator = ",")

... except that `Polars.DataFrame.unique()` appears to be flaky, so we'll use Bash commands.

In [7]:
!cat os_data.csv | sort -u -t, -k1,1 > foo.csv
!mv foo.csv os_data.csv

Also extract the risk information from Open Sanctions, which will populate nodes in a different table.

In [8]:
df: pl.DataFrame = df_src.explode("RISKS")

df = df.with_columns(
    pl.when(pl.col("RISKS").is_not_null())
    .then(
        pl.coalesce(
            pl.col("RISKS").struct.field("TOPIC"),
        )
    )
    .otherwise(None)
    .alias("topic")
)

df = df.select(
    pl.col("id"),
    pl.col("topic"),
).drop_nulls(subset=["topic"])

df

shape: (29, 2)
┌─────────────────────────────────┬─────────────────┐
│ id                              ┆ topic           │
│ ---                             ┆ ---             │
│ str                             ┆ str             │
╞═════════════════════════════════╪═════════════════╡
│ sz:ds_open-sanctions_NK-25vyVF… ┆ corp.disqual    │
│ sz:ds_open-sanctions_NK-auyPsL… ┆ sanction.linked │
│ sz:ds_open-sanctions_NK-cf4Q3K… ┆ sanction.linked │
│ sz:ds_open-sanctions_NK-dNNN56… ┆ role.rca        │
│ sz:ds_open-sanctions_NK-dNNN56… ┆ sanction        │
│ …                               ┆ …               │
│ sz:ds_open-sanctions_ru-inn-77… ┆ sanction.linked │
│ sz:ds_open-sanctions_rupep-com… ┆ sanction.linked │
│ sz:ds_open-sanctions_rupep-com… ┆ sanction.linked │
│ sz:ds_open-sanctions_rupep-com… ┆ sanction.linked │
│ sz:ds_open-sanctions_rupep-com… ┆ sanction.linked │
└─────────────────────────────────┴─────────────────┘

## Extract risk relations

Serialize this dataframe to the `os_risk.csv` CSV file.

In [9]:
df.write_csv(pathlib.Path("os_risk.csv"), separator = ",")

## Parse the Open Ownership dataset

In [10]:
df_src: pl.DataFrame = pl.read_ndjson("data/open-ownership.json")

# normalize IRIs for connecting later
df_src = df_src.replace_column(
    1,
    pl.Series(
        "id",
        map(lambda s: "sz:ds_open-ownership_" + s, df_src["RECORD_ID"])
    ),
)

df_src = df_src.replace_column(
    3,
    pl.Series(
        "class",
        map(lambda s: "sz:" + s.capitalize(), df_src["RECORD_TYPE"])
    ),
)

df_src

shape: (316, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ DATA_SOUR ┆ id        ┆ statement ┆ class     ┆ … ┆ REGISTRAT ┆ dissoluti ┆ REGISTRAT ┆ DATE_OF_ │
│ CE        ┆ ---       ┆ Date      ┆ ---       ┆   ┆ ION_DATE  ┆ onDate    ┆ ION_COUNT ┆ BIRTH    │
│ ---       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ RY        ┆ ---      │
│ str       ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2023-06-1 ┆ sz:Organi ┆ … ┆ 2020-03-1 ┆ null      ┆ GB        ┆ null     │
│ RSHIP     ┆ n-ownersh ┆ 8         ┆ zation    ┆   ┆ 8         ┆           ┆           ┆          │
│           ┆ ip_100945 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 215…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2023-06-1 ┆ sz:Organi ┆ … ┆ 2019-08-2 ┆ 2022-10-1 ┆ GB        ┆ null     │
│ RSHIP     ┆ n-ownersh ┆ 8         ┆ zation    ┆   ┆ 0         ┆ 1         ┆           ┆          │
│           ┆ ip_101656 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 327…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2023-06-1 ┆ sz:Organi ┆ … ┆ 2019-08-2 ┆ 2022-10-1 ┆ GB        ┆ null     │
│ RSHIP     ┆ n-ownersh ┆ 8         ┆ zation    ┆   ┆ 0         ┆ 1         ┆           ┆          │
│           ┆ ip_101656 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 327…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2024-01-0 ┆ sz:Person ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ RSHIP     ┆ n-ownersh ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ip_102644 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 597…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2023-06-1 ┆ sz:Person ┆ … ┆ null      ┆ null      ┆ null      ┆ 1993-02- │
│ RSHIP     ┆ n-ownersh ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│           ┆ ip_103690 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 294…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2024-01-0 ┆ sz:Organi ┆ … ┆ 2010-06-3 ┆ null      ┆ DK        ┆ null     │
│ RSHIP     ┆ n-ownersh ┆ 3         ┆ zation    ┆   ┆ 0         ┆           ┆           ┆          │
│           ┆ ip_966913 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 957…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2024-01-0 ┆ sz:Organi ┆ … ┆ 2010-06-3 ┆ null      ┆ DK        ┆ null     │
│ RSHIP     ┆ n-ownersh ┆ 3         ┆ zation    ┆   ┆ 0         ┆           ┆           ┆          │
│           ┆ ip_966913 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 957…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2023-06-1 ┆ sz:Person ┆ … ┆ null      ┆ null      ┆ null      ┆ 1981-02- │
│ RSHIP     ┆ n-ownersh ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│           ┆ ip_969413 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 650…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2023-06-1 ┆ sz:Person ┆ … ┆ null      ┆ null      ┆ null      ┆ 1962-08- │
│ RSHIP     ┆ n-ownersh ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│           ┆ ip_980496 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 272…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ OPEN-OWNE ┆ sz:ds_ope ┆ 2023-07-2 ┆ sz:Person ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ RSHIP     ┆ n-ownersh ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ip_985819 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 603…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
# normalize names from nested attributes
df = df_src.explode("NAMES").explode("ATTRIBUTES")
    
# extract nationality - from person or organization
df = df.with_columns(
    pl.when(pl.col("class") == "sz:Person")
    .then(pl.col("ATTRIBUTES").struct.field("NATIONALITY"))
    .when(pl.col("class") == "sz:Organization")
    .then(pl.col("REGISTRATION_COUNTRY"))
    .otherwise(None)
    .alias("country")
)

# extract name - from person or organization,
# filter records which lack a name
df = df.with_columns(
    pl.when(pl.col("class") == "sz:Person")
    .then(pl.col("PRIMARY_NAME_FULL"))
    .when(pl.col("class") == "sz:Organization")
    .then(pl.col("NAMES").struct.field("PRIMARY_NAME_ORG"))
    .otherwise(None)
    .alias("descrip")
).drop_nulls("descrip")

# normalize addresses from nested attributes
df = df.explode("ADDRESSES")

df = df.with_columns(
    pl.when(pl.col("class") == "sz:Person")
    .then(pl.col("ADDRESSES").struct.field("ADDR_FULL"))
    .when(pl.col("class") == "sz:Organization")
    .then(pl.col("ADDRESSES").struct.field("ADDR_FULL"))
    .otherwise(None)
    .alias("address")
)

# select the results
df = df.select(
    pl.col("id"),
    pl.col("descrip"),
    pl.col("class"),
    pl.col("address"),
    pl.col("country"),
).unique().sort("id")

df

shape: (258, 5)
┌───────────────────────┬───────────────────────┬─────────────────┬──────────────────────┬─────────┐
│ id                    ┆ descrip               ┆ class           ┆ address              ┆ country │
│ ---                   ┆ ---                   ┆ ---             ┆ ---                  ┆ ---     │
│ str                   ┆ str                   ┆ str             ┆ str                  ┆ str     │
╞═══════════════════════╪═══════════════════════╪═════════════════╪══════════════════════╪═════════╡
│ sz:ds_open-ownership_ ┆ GOLD WYNN UK HOLDINGS ┆ sz:Organization ┆ C/O Fladgate Llp, 16 ┆ GB      │
│ 100945215…            ┆ LIMITED               ┆                 ┆ Great Que…           ┆         │
│ sz:ds_open-ownership_ ┆ UPSIDE TECHNOLOGY     ┆ sz:Organization ┆ Apt 52, 3 Whitehall  ┆ GB      │
│ 101656327…            ┆ LIMITED               ┆                 ┆ Court, Lon…          ┆         │
│ sz:ds_open-ownership_ ┆ Kenneth Kurt Hansen   ┆ sz:Person       ┆ Finderupvej 61,      ┆ DK      │
│ 102644597…            ┆                       ┆                 ┆ Kastrup, 2770        ┆         │
│ sz:ds_open-ownership_ ┆ Daniel Simmons        ┆ sz:Person       ┆ 17 St Andrews        ┆ GB      │
│ 103690294…            ┆                       ┆                 ┆ Crescent, Cardif…    ┆         │
│ sz:ds_open-ownership_ ┆ Wyndham James         ┆ sz:Person       ┆ Apt 52, 3, Whitehall ┆ GB      │
│ 103906995…            ┆ Alexander Plumpt…     ┆                 ┆ Court, Lo…           ┆         │
│ …                     ┆ …                     ┆ …               ┆ …                    ┆ …       │
│ sz:ds_open-ownership_ ┆ Milla Kier Meraki     ┆ sz:Person       ┆ Valby Langgade 222,  ┆ DK      │
│ 953272446…            ┆ Hansen                ┆                 ┆ 1, Valby, …          ┆         │
│ sz:ds_open-ownership_ ┆ Ejendomsselskabet     ┆ sz:Organization ┆ Gotlandsvej 5,       ┆ DK      │
│ 966913957…            ┆ Gotland A/S           ┆                 ┆ Svendborg, 5700      ┆         │
│ sz:ds_open-ownership_ ┆ Barry Halstead        ┆ sz:Person       ┆ Barry Halstead, Flat ┆ GB      │
│ 969413650…            ┆                       ┆                 ┆ 1, 505 Fu…           ┆         │
│ sz:ds_open-ownership_ ┆ Jeffrey Mark          ┆ sz:Person       ┆ 369, Franklin        ┆ CA      │
│ 980496272…            ┆ Weinzweig             ┆                 ┆ Street, Buffalo,…    ┆         │
│ sz:ds_open-ownership_ ┆ Mathilde Thrane       ┆ sz:Person       ┆ Thorvaldsensgade 32, ┆ DK      │
│ 985819603…            ┆ Roussau Christ…       ┆                 ┆ 4, Aarhus…           ┆         │
└───────────────────────┴───────────────────────┴─────────────────┴──────────────────────┴─────────┘

Serialize this dataframe to the `oo_data.csv` CSV file.

In [12]:
df.write_csv(pathlib.Path("oo_data.csv"), separator = ",")

## Extract UBO relations

Open Ownership describes [_ultimate beneficial ownership_](https://www.beneficialownership.co.uk/) (UBO) details, which provides the "link" category in the generalized anti-fraud data model.

First we'll save the primary keys for the known records in this dataset slice, so that edges are constrained to records that are available here.

In [13]:
ubo_ids: set[ str ] = set(df.select("id").to_series().to_list())

In [14]:
df = df_src.explode("RELATIONSHIPS")

df = df.with_columns([
    pl.col("id").alias("src_id"),
    pl.col("RELATIONSHIPS").struct.field("REL_POINTER_KEY").alias("dst_id"),
    pl.col("RELATIONSHIPS").struct.field("REL_POINTER_ROLE").alias("role"),
    pl.col("RELATIONSHIPS").struct.field("REL_POINTER_FROM_DATE").alias("date"),
]).drop_nulls(subset=["src_id", "dst_id", "role"])

df = df.select(
    pl.col("src_id"),
    pl.col("dst_id"),
    pl.col("role"),
    pl.col("date"),
).sort("src_id", "dst_id")

# normalize IRIs for connecting later
df = df.replace_column(
    1,
    pl.Series(
        "dst_id",
        map(lambda s: "sz:ds_open-ownership_" + s, df["dst_id"])
    ),
)

# only include relationships where both records are available
df = df.filter(
    pl.col("src_id").is_in(ubo_ids) & pl.col("dst_id").is_in(ubo_ids)
)

df

shape: (539, 4)
┌────────────────────────────┬────────────────────────────┬───────────────────────────┬────────────┐
│ src_id                     ┆ dst_id                     ┆ role                      ┆ date       │
│ ---                        ┆ ---                        ┆ ---                       ┆ ---        │
│ str                        ┆ str                        ┆ str                       ┆ str        │
╞════════════════════════════╪════════════════════════════╪═══════════════════════════╪════════════╡
│ sz:ds_open-ownership_10094 ┆ sz:ds_open-ownership_75845 ┆ shareholding 75% 100%     ┆ 2020-03-18 │
│ 5215…                      ┆ 9180…                      ┆                           ┆            │
│ sz:ds_open-ownership_10094 ┆ sz:ds_open-ownership_75845 ┆ appointment_of_board      ┆ 2020-03-18 │
│ 5215…                      ┆ 9180…                      ┆                           ┆            │
│ sz:ds_open-ownership_10094 ┆ sz:ds_open-ownership_75845 ┆ voting_rights 75% 100%    ┆ 2020-03-18 │
│ 5215…                      ┆ 9180…                      ┆                           ┆            │
│ sz:ds_open-ownership_10165 ┆ sz:ds_open-ownership_59816 ┆ shareholding 75% 100%     ┆ 2019-08-20 │
│ 6327…                      ┆ 1773…                      ┆                           ┆            │
│ sz:ds_open-ownership_10165 ┆ sz:ds_open-ownership_59816 ┆ voting_rights 75% 100%    ┆ 2019-08-20 │
│ 6327…                      ┆ 1773…                      ┆                           ┆            │
│ …                          ┆ …                          ┆ …                         ┆ …          │
│ sz:ds_open-ownership_94470 ┆ sz:ds_open-ownership_28795 ┆ other_influence_or_contro ┆ 2020-04-14 │
│ 5691…                      ┆ 7459…                      ┆ l                         ┆            │
│ sz:ds_open-ownership_96691 ┆ sz:ds_open-ownership_10264 ┆ shareholding 15%          ┆ 2019-12-19 │
│ 3957…                      ┆ 4597…                      ┆                           ┆            │
│ sz:ds_open-ownership_96691 ┆ sz:ds_open-ownership_10264 ┆ voting_rights 15%         ┆ 2019-12-19 │
│ 3957…                      ┆ 4597…                      ┆                           ┆            │
│ sz:ds_open-ownership_96691 ┆ sz:ds_open-ownership_10264 ┆ shareholding 15%          ┆ 2019-12-19 │
│ 3957…                      ┆ 4597…                      ┆                           ┆            │
│ sz:ds_open-ownership_96691 ┆ sz:ds_open-ownership_10264 ┆ voting_rights 15%         ┆ 2019-12-19 │
│ 3957…                      ┆ 4597…                      ┆                           ┆            │
└────────────────────────────┴────────────────────────────┴───────────────────────────┴────────────┘

Serialize this dataframe to the `oo_ubos.csv` CSV file.

In [15]:
df.write_csv(pathlib.Path("oo_ubos.csv"), separator = ",")

---