# Notebook 2: Transform data records into dataframes

Import the Python library dependencies.

In [8]:
import pathlib

import polars as pl
import watermark

Run a "watermark" to show which library versions are used in this notebook's runtime environment.

In [9]:
%load_ext watermark
%watermark
%watermark --iversions

Last updated: 2025-11-11T18:46:03.355621-08:00

Python implementation: CPython
Python version       : 3.13.8
IPython version      : 9.1.0

Compiler    : Clang 17.0.0 (clang-1700.0.13.3)
OS          : Darwin
Release     : 24.6.0
Machine     : arm64
Processor   : arm
CPU cores   : 14
Architecture: 64bit

watermark: 2.5.0
polars   : 1.29.0

## Parse the Open Sanctions dataset

In [2]:
df_src: pl.DataFrame = pl.read_ndjson("data/open-sanctions.json")

# normalize the IRIs for joining
df_src = df_src.replace_column(
    1,
    pl.Series(
        "id",
        map(lambda s: "sz:ds_open-sanctions_" + s, df_src["RECORD_ID"])
    ),
)

df_src = df_src.replace_column(
    2,
    pl.Series(
        "class",
        map(lambda s: "sz:" + s.capitalize(), df_src["RECORD_TYPE"])
    ),
)

In [3]:
df_src

shape: (24, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ DATA_SOUR ┆ id        ┆ class     ┆ LAST_CHAN ┆ … ┆ SOURCE_LI ┆ RELATIONS ┆ URL       ┆ CONTACTS │
│ CE        ┆ ---       ┆ ---       ┆ GE        ┆   ┆ NKS       ┆ HIPS      ┆ ---       ┆ ---      │
│ ---       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ list[str │
│ str       ┆           ┆           ┆ str       ┆   ┆ list[stru ┆ list[stru ┆           ┆ uct[1]]  │
│           ┆           ┆           ┆           ┆   ┆ ct[1]]    ┆ ct[5]]    ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Person ┆ 2024-07-3 ┆ … ┆ [{"https: ┆ [{null,nu ┆ https://w ┆ null     │
│ TIONS     ┆ n-sanctio ┆           ┆ 0T16:41:1 ┆   ┆ //find-an ┆ ll,"Direc ┆ ww.opensa ┆          │
│           ┆ ns_NK-25v ┆           ┆ 4         ┆   ┆ d-update. ┆ torship", ┆ nctions.o ┆          │
│           ┆ yVF…      ┆           ┆           ┆   ┆ com…      ┆ "OP…      ┆ rg/…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2025-01-0 ┆ … ┆ null      ┆ [{"OPEN-S ┆ https://w ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 7T00:33:0 ┆   ┆           ┆ ANCTIONS" ┆ ww.opensa ┆          │
│           ┆ ns_NK-3p3 ┆           ┆ 3         ┆   ┆           ┆ ,"NK-3p3m ┆ nctions.o ┆          │
│           ┆ mmV…      ┆           ┆           ┆   ┆           ┆ mVW…      ┆ rg/…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-03-0 ┆ … ┆ null      ┆ [{"OPEN-S ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 3T19:51:2 ┆   ┆           ┆ ANCTIONS" ┆ pensancti ┆          │
│           ┆ ns_NK-auy ┆           ┆ 9         ┆   ┆           ┆ ,"NK-auyP ┆ ons.org/e ┆          │
│           ┆ PsL…      ┆           ┆           ┆   ┆           ┆ sLr…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-03-0 ┆ … ┆ [{"http:/ ┆ [{"OPEN-S ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 3T08:46:3 ┆   ┆ /business ┆ ANCTIONS" ┆ pensancti ┆          │
│           ┆ ns_NK-cf4 ┆           ┆ 1         ┆   ┆ .data.gov ┆ ,"NK-cf4Q ┆ ons.org/e ┆          │
│           ┆ Q3K…      ┆           ┆           ┆   ┆ .uk…      ┆ 3Kc…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Person ┆ 2025-02-1 ┆ … ┆ [{"https: ┆ [{null,nu ┆ https://w ┆ null     │
│ TIONS     ┆ n-sanctio ┆           ┆ 0T15:38:0 ┆   ┆ //sanctio ┆ ll,"Famil ┆ ww.opensa ┆          │
│           ┆ ns_NK-dNN ┆           ┆ 2         ┆   ┆ nssearch. ┆ y","OPEN- ┆ nctions.o ┆          │
│           ┆ N56…      ┆           ┆           ┆   ┆ ofa…      ┆ SAN…      ┆ rg/…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{"OPEN-S ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ANCTIONS" ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ ,"rupep-c ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ omp…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{"OPEN-S ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ANCTIONS" ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ ,"rupep-c ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ omp…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{"OPEN-S ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ANCTIONS" ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ ,"rupep-c ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ omp…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{"OPEN-S ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ANCTIONS" ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ ,"rupep-c ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ omp…      ┆ nti…      ┆          │
│ OPEN-SANC ┆ sz:ds_ope ┆ sz:Organi ┆ 2024-01-1 ┆ … ┆ null      ┆ [{"OPEN-S ┆ https://o ┆ null     │
│ TIONS     ┆ n-sanctio ┆ zation    ┆ 8T00:00:0 ┆   ┆           ┆ ANCTIONS" ┆ pensancti ┆          │
│           ┆ ns_rupep- ┆           ┆ 0         ┆   ┆           ┆ ,"rupep-c ┆ ons.org/e ┆          │
│           ┆ com…      ┆           ┆           ┆   ┆           ┆ omp…      ┆ nti…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
# normalize the names from nested attributes
df: pl.DataFrame = df_src.explode("NAMES")

df = df.with_columns(
    pl.when(pl.col("NAMES").struct.field("NAME_TYPE") == "PRIMARY_NAME_FULL")
    .then(pl.col("NAMES").struct.field("NAME_TYPE"))
    .when(pl.col("NAMES").struct.field("NAME_TYPE") == "PRIMARY")
    .then(
        pl.coalesce(
            pl.col("NAMES").struct.field("NAME_FULL"),
            pl.col("NAMES").struct.field("NAME_ORG")
        )
    )
    .otherwise(None)
    .alias("descrip")
)

# select the columns to keep
df = df.select(
        pl.col("id"),
        pl.col("descrip"),
        pl.col("class"),
        pl.col("ADDRESSES").alias("addr"),
        pl.col("URL").alias("url"),
    ).drop_nulls(subset=["descrip"]).sort("id")

df = df.unique(subset = ["id", "descrip"]).sort("id")

# normalize the addresses from nested attributes
df = df.explode("addr")

df = df.with_columns(
    pl.when(pl.col("addr").is_not_null())
    .then(
        pl.coalesce(
            pl.col("addr").struct.field("ADDR_FULL"),
        )
    )
    .otherwise(None)
    .alias("addr")
)

df

shape: (75, 5)
┌────────────────────┬───────────────────┬─────────────────┬───────────────────┬───────────────────┐
│ id                 ┆ descrip           ┆ class           ┆ addr              ┆ url               │
│ ---                ┆ ---               ┆ ---             ┆ ---               ┆ ---               │
│ str                ┆ str               ┆ str             ┆ str               ┆ str               │
╞════════════════════╪═══════════════════╪═════════════════╪═══════════════════╪═══════════════════╡
│ sz:ds_open-sanctio ┆ Abassin BADSHAH   ┆ sz:Person       ┆ 31 Quernmore      ┆ https://www.opens │
│ ns_NK-25vyVF…      ┆                   ┆                 ┆ Close, Bromley,   ┆ anctions.org/…    │
│                    ┆                   ┆                 ┆ K…                ┆                   │
│ sz:ds_open-sanctio ┆ LMAR (GB) LTD     ┆ sz:Organization ┆ 31 Quernmore      ┆ https://www.opens │
│ ns_NK-3p3mmV…      ┆                   ┆                 ┆ Close, Bromley,   ┆ anctions.org/…    │
│                    ┆                   ┆                 ┆ K…                ┆                   │
│ sz:ds_open-sanctio ┆ Gulnara           ┆ sz:Person       ┆ MOSCOW, RUS,      ┆ https://www.opens │
│ ns_NK-L2UmsZ…      ┆ Suleimanova       ┆                 ┆ 123430            ┆ anctions.org/…    │
│                    ┆ KERIMOVA          ┆                 ┆                   ┆                   │
│ sz:ds_open-sanctio ┆ Gulnara           ┆ sz:Person       ┆ Apt 270, Build.   ┆ https://www.opens │
│ ns_NK-L2UmsZ…      ┆ Suleimanova       ┆                 ┆ 31, Pyatnitsko…   ┆ anctions.org/…    │
│                    ┆ KERIMOVA          ┆                 ┆                   ┆                   │
│ sz:ds_open-sanctio ┆ Gulnara           ┆ sz:Person       ┆ Apt 270, Build.   ┆ https://www.opens │
│ ns_NK-L2UmsZ…      ┆ Suleimanova       ┆                 ┆ 31, Pyatnitsko…   ┆ anctions.org/…    │
│                    ┆ KERIMOVA          ┆                 ┆                   ┆                   │
│ …                  ┆ …                 ┆ …               ┆ …                 ┆ …                 │
│ sz:ds_open-sanctio ┆ Vencher           ┆ sz:Organization ┆ ПЕР.              ┆ https://opensanct │
│ ns_rupep-com…      ┆ Management        ┆                 ┆ СТАРОМОНЕТНЫЙ,    ┆ ions.org/enti…    │
│                    ┆ Limited LLC       ┆                 ┆ Москва            ┆                   │
│ sz:ds_open-sanctio ┆ Natsionalnaia     ┆ sz:Organization ┆ переулок          ┆ https://opensanct │
│ ns_rupep-com…      ┆ Kinoset LLC       ┆                 ┆ Старомонетны,     ┆ ions.org/enti…    │
│                    ┆                   ┆                 ┆ Москва            ┆                   │
│ sz:ds_open-sanctio ┆ Zareche-Estate    ┆ sz:Organization ┆ улица Народная,   ┆ https://opensanct │
│ ns_rupep-com…      ┆ LLC               ┆                 ┆ Москва            ┆ ions.org/enti…    │
│ sz:ds_open-sanctio ┆ NUGGET CAPITAL    ┆ sz:Organization ┆ null              ┆ https://opensanct │
│ ns_rupep-com…      ┆ PLC               ┆                 ┆                   ┆ ions.org/enti…    │
│ sz:ds_open-sanctio ┆ POLYUS FINANCE    ┆ sz:Organization ┆ null              ┆ https://opensanct │
│ ns_rupep-com…      ┆ PLC               ┆                 ┆                   ┆ ions.org/enti…    │
└────────────────────┴───────────────────┴─────────────────┴───────────────────┴───────────────────┘

Serialize the dataframe as the `os_data.csv` CSV file.

In [5]:
df.write_csv(pathlib.Path("os_data.csv"), separator = ",")

Also extract the risks from Open Sanctions, which will become a separate table.

In [6]:
df: pl.DataFrame = df_src.explode("RISKS")

df = df.with_columns(
    pl.when(pl.col("RISKS").is_not_null())
    .then(
        pl.coalesce(
            pl.col("RISKS").struct.field("TOPIC"),
        )
    )
    .otherwise(None)
    .alias("topic")
)

df = df.select(
    pl.col("id"),
    pl.col("topic"),
).drop_nulls(subset=["topic"])

df

shape: (29, 2)
┌─────────────────────────────────┬─────────────────┐
│ id                              ┆ topic           │
│ ---                             ┆ ---             │
│ str                             ┆ str             │
╞═════════════════════════════════╪═════════════════╡
│ sz:ds_open-sanctions_NK-25vyVF… ┆ corp.disqual    │
│ sz:ds_open-sanctions_NK-auyPsL… ┆ sanction.linked │
│ sz:ds_open-sanctions_NK-cf4Q3K… ┆ sanction.linked │
│ sz:ds_open-sanctions_NK-dNNN56… ┆ role.rca        │
│ sz:ds_open-sanctions_NK-dNNN56… ┆ sanction        │
│ …                               ┆ …               │
│ sz:ds_open-sanctions_ru-inn-77… ┆ sanction.linked │
│ sz:ds_open-sanctions_rupep-com… ┆ sanction.linked │
│ sz:ds_open-sanctions_rupep-com… ┆ sanction.linked │
│ sz:ds_open-sanctions_rupep-com… ┆ sanction.linked │
│ sz:ds_open-sanctions_rupep-com… ┆ sanction.linked │
└─────────────────────────────────┴─────────────────┘

Serialize the dataframe as the `os_risk.csv` CSV file.

In [7]:
df.write_csv(pathlib.Path("os_risk.csv"), separator = ",")